version: '3.7'

services:
  db: 
    container_name: my-sql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    networks:
      - challenge-network

  app:
    depends_on: 
      - db
    restart: always
    container_name: node-app
    build: ./nodejs/
    networks:
      - challenge-network
  ngnix:
    restart: always
    container_name: nginx-server
    build: ./nginx/
    networks:
      - challenge-network
    ports:
      - 8080:80

networks:
  challenge-network:
    name: challenge-network
    driver: bridge